//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pekarniya.BDkon
{
    using System;
    using System.Collections.Generic;
    
    public partial class goods_cashier
    {
        public int id { get; set; }
        public Nullable<int> id_goods { get; set; }
        public Nullable<int> id_cashier { get; set; }
        public Nullable<int> quantity { get; set; }
        public string cost { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual cashier cashier { get; set; }
        public virtual goods goods { get; set; }
    }
}
